In [1]:
import pandas as pd
import numpy as np

In [2]:
#Create a Dictionary of series

d = {'Name':pd.Series(['Tom','James','Ricky','Vin','Steve','Smith','Jack']),
     'Age':pd.Series([25,26,25,23,30,29,23]),
     'Rating':pd.Series([4.23,3.24,3.98,2.56,3.20,4.6,3.8])}

In [3]:
#find shape of above series
df = pd.DataFrame(d)
df.shape

(7, 3)

In [4]:
df.size

21

In [5]:
df.head()

Name  Age  Rating
0    Tom   25    4.23
1  James   26    3.24
2  Ricky   25    3.98
3    Vin   23    2.56
4  Steve   30    3.20

In [6]:
df.tail()

Name  Age  Rating
2  Ricky   25    3.98
3    Vin   23    2.56
4  Steve   30    3.20
5  Smith   29    4.60
6   Jack   23    3.80

In [7]:
df.dtypes

Name       object
Age         int64
Rating    float64
dtype: object

2. Create a Dataframe

In [8]:
ipl_data = {'Team': ['Riders', 'Riders', 'Devils', 'Devils', 'Kings', 'Kings', 'Kings', 'Kings', 'Riders', 'Royals', 'Royals', 'Riders'], 
            'Rank': [1, 2, 2, 3, 3,4 ,1 ,1,2 , 4,1,2], 
            'Year': [2014,2015,2014,2015,2014,2015,2016,2017,2016,2014,2015,2017], 
            'Points':[876,789,863,673,741,812,756,788,694,701,804,690]}

In [9]:
df = pd.DataFrame(ipl_data)

In [10]:
print(df)

      Team  Rank  Year  Points
0   Riders     1  2014     876
1   Riders     2  2015     789
2   Devils     2  2014     863
3   Devils     3  2015     673
4    Kings     3  2014     741
5    Kings     4  2015     812
6    Kings     1  2016     756
7    Kings     1  2017     788
8   Riders     2  2016     694
9   Royals     4  2014     701
10  Royals     1  2015     804
11  Riders     2  2017     690


In [11]:
#Divide the above df into three groups (Hint: apply Groupby function)
df.groupby('Team').groups

{'Devils': [2, 3], 'Kings': [4, 5, 6, 7], 'Riders': [0, 1, 8, 11], 'Royals': [9, 10]}

Q:2: Numpy:

In [12]:
a = np.array([10,20,30]) 
b = np.array([3,5,7])

In [13]:
#Apply power function #a to the power of b
np.power(a,b)

array([     1000,   3200000, 395163520])

In [14]:
#Apply mod() function
np.mod(a,b)

array([1, 0, 2])

In [15]:
#Apply remainder() function
np.remainder(a,b)

array([1, 0, 2])